# -*- coding: utf-8 -*-
FILES = {
    # ------------------------------------------------------------------ unit tests (05_explanation_api/tests)
    "05_explanation_api/tests/__init__.py": {
        "title": "علامة حزمة الفحوصات",
        "one": "ملف فاضي بيخلّي مجلد tests حزمة Python.",
        "role": "ما فيه كود. فايدته إنك تقدر تشغّل ملف فحص لحاله بالاسم، من جوّا 05_explanation_api: python -m unittest tests.test_api -v",
        "how": [
            "Python بيلاقي __init__.py فبيعتبر tests حزمة.",
            "unittest بيقدر يوصل لـ tests.test_api و tests.test_service وغيرهم بالاسم.",
        ],
        "items": {},
    },

    "05_explanation_api/tests/test_api.py": {
        "title": "فحوصات أبواب السيرفر",
        "one": "بيتأكد إن كل باب (endpoint) بالسيرفر بيرد صح: الصحة، التوليد، الكتب، الدروس، الرسومات، الصفحة، والأخطاء.",
        "role": "بيفحص main.app و api/routes.py من برّا، كأنه الفرونت إند، عن طريق TestClient. تشغيل (من جوّا 05_explanation_api): python -m unittest tests.test_api -v ، وبالبيئة اللي ما فيها FastAPI: PYTHONPATH=tests/local_stub_only_for_sandbox python -m unittest tests.test_api -v",
        "how": [
            "بيحط EXPLAIN_SEED=0 عشان السيرفر ما يعمل الكتب النموذجية لحاله.",
            "بيحط EXPLAIN_DATA_DIR على مجلد مؤقت عشان ما يلمس البيانات الحقيقية.",
            "بيحاول يستورد TestClient و app؛ إذا FastAPI مش منزّل، كل الفحوصات هون بتتخطّى (فحوصات الخدمة بتضل تشتغل).",
            "مرة وحدة بالبداية بيبعت جراف كتاب الرياضيات لـ POST /explanations/generate.",
            "كل فحص بيستعمل هالجواب وبيطلب باب معيّن وبيقارن الكود والمحتوى.",
            "بالآخر بيمسح المجلد المؤقت.",
        ],
        "ideas": [
            ["TestClient", "بيبعت طلبات للسيرفر من جوّا Python بدون شبكة وبدون ما تشغّل السيرفر فعلياً."],
            ["skipUnless", "بيتخطّى الفحص (مش بيفشّله) إذا الشرط مش متحقق، هون: FastAPI مش منزّل."],
            ["setUpClass", "بيشتغل مرة وحدة قبل كل فحوصات الكلاس، عشان التوليد الغالي ما يتكرر."],
        ],
        "tip": "إذا شفت الفحوصات skipped، يعني FastAPI مش منزّل: نزّله بـ pip install -r requirements.txt.",
        "items": {
            "TestAPI": "كلاس فحوصات الأبواب؛ بيتخطّى كله إذا FastAPI مش موجود.",
            "TestAPI.setUpClass": "بيعمل TestClient(app) وبيبعت جراف الرياضيات مرة وحدة لـ /explanations/generate.",
            "TestAPI.tearDownClass": "بيمسح مجلد البيانات المؤقت.",
            "TestAPI.test_health": "GET /health لازم يرد 200 و status = ok.",
            "TestAPI.test_generate": "التوليد رد 200، وطلع 4 دروس وأكثر من 30 مشهد.",
            "TestAPI.test_generate_bad_requests": "طلب فاضي بيرجع 400، وgraph_path لملف مش موجود بيرجع 404.",
            "TestAPI.test_books_lessons_lesson_concept_picture": "بيمشي الطريق كامل: /books ثم دروس الكتاب ثم درس ثم مفهوم ثم رسمة المفهوم، ولازم الرسمة تطلع SVG.",
            "TestAPI.test_not_found": "درس أو كتاب أو رسمة مش موجودين بيرجعوا 404.",
            "TestAPI.test_home_page": "GET / بيرجع صفحة HTML فيها «سيرفر الشرح التفاعلي».",
            "TestAPI.test_the_interactive_page_from_the_server": "/explain/{book} بيرجع الصفحة وفيها const DATA = ، و/explain لكل الكتب، وكتاب مش موجود 404، و/explain-data بيرجع جراف واحد، وpage_url صح.",
            "TestAPI.test_a_new_subject_through_the_api": "جراف الحاسوب (مادة جديدة) بياخد هويته (family = computer وصوت chip)، بيبيّن بالصفحة وبـ /books، وبعد DELETE صفحته بترجع 404.",
            "TestAPI.test_picture_per_age_stage": "رسمة 🐝 بـ stage=senior فيها القاعدة اللي بتخفي الوجه.",
            "TestAPI.test_contract": "/scene-kinds فيه نوع meet وفيه relation.",
        },
    },

    "05_explanation_api/tests/test_lego_api.py": {
        "title": "فحوصات الليغو بالسيرفر",
        "one": "بيتأكد إن مادة جديدة كلماتها ما بتعرفها ولا رسمة ولا قطعة بتاخد رسومات ليغو بنداء موديل واحد، وإن المعلم بيقدر يغيّرها أو يرفضها.",
        "role": "بيفحص دوال الليغو بـ core/service.py (generate مع llm، lego_library، lego_parts، lego_choose، get_art) وcore/art.py و02_question_factory/lego.py، وأبواب /lego/... بالسيرفر. الموديل وهمي، ما بدها مفاتيح. تشغيل (من جوّا 05_explanation_api): python -m unittest tests.test_lego_api -v",
        "how": [
            "بياخد جراف الحاسوب وبيغيّر أسماء مفاهيمه لكلمات طبخ (COOKING) وبيسمّي الكتاب cook_g7.",
            "قبل التوليد بيسجّل إن كل كلمة طبخ ما إلها غير شخصية المادة (subj:).",
            "بيولّد الكتاب مع موديل وهمي (Model) بيرد بس على سؤال الليغو.",
            "الفحوصات مرقّمة 1 لـ 6 عشان تمشي بالترتيب: البناء، الرسم، المكتبة، اختيار المعلم، الرفض، ثم HTTP.",
            "بالآخر بيمسح cook_g7 لأن ملفات الفحص الثانية بتشارك نفس مجلد البيانات.",
        ],
        "ideas": [
            ["موديل وهمي", "دالة بتتصرّف كأنها الموديل الحقيقي وبترجع جواب جاهز، عشان نفحص بدون مفاتيح وبدون تكلفة."],
            ["مكتبة الليغو", "ملف بيحفظ كل رسمة انبنت من قطع، فبتكبر مع الوقت والمعلم بيراجعها."],
        ],
        "items": {
            "COOKING": "9 كلمات طبخ ما بتعرفها ولا رسمة عنا ولا قطعة ليغو.",
            "cooking_graph": "بيرجع نسخة من جراف الحاسوب بأسماء طبخ ومادة «الطبخ» وid = cook_g7.",
            "Model": "موديل وهمي: بيجاوب بس على سؤال بناء الليغو وبيعد كم مرة انسأل.",
            "Model.__init__": "بيبدأ عدّاد lego_calls من صفر.",
            "Model.__call__": "إذا السؤال مش عن الليغو بيرجع فاضي؛ غير هيك بيقرأ الأسماء من السؤال وبيعطي لكل اسم خيارين: pot مع spark، و bag.",
            "TestLegoServer": "كلاس فحوصات الليغو عبر الخدمة والسيرفر.",
            "TestLegoServer.setUpClass": "بيسجّل الرسومات قبل، وبيولّد كتاب الطبخ مع الموديل الوهمي.",
            "TestLegoServer.tearDownClass": "بيمسح كتاب cook_g7.",
            "TestLegoServer.test_1_one_call_and_every_concept_is_built": "نداء واحد للموديل لكل الكتاب، و9 مفاهيم انبنت، وكل رسومات الصفحة صارت lego:pot:spark:.",
            "TestLegoServer.test_2_the_server_draws_them": "السيرفر بيرسم مفتاح الليغو SVG كامل فيه style والشارة بمكانها، وقطعة غلط (pizza) ما بترسم إشي.",
            "TestLegoServer.test_3_library_grows_and_lists_suggestions": "المكتبة فيها كل كلمات الطبخ، كل وحدة حالتها auto ومعها صورتين اقتراحات، وpot من القطع.",
            "TestLegoServer.test_4_teacher_picks_another_and_the_page_changes": "المعلم بيختار الاقتراح الثاني للعجين فبتصير lego:bag: والدروس والصفحة بتتحدّث.",
            "TestLegoServer.test_5_teacher_says_no": "رفض الشوي بيرجّعه لشخصية المادة؛ اسم مش موجود NotFound، ورقم اقتراح غلط BadInput.",
            "TestLegoServer.test_6_http": "نفس الإشي عبر الأبواب: /lego/parts و /lego/drawings و /art/lego... و /lego/drawings/choose (و404 لاسم غلط). بده FastAPI.",
        },
    },

    "05_explanation_api/tests/test_llm_scenes.py": {
        "title": "فحوصات مشاهد الموديل",
        "one": "بيتأكد إن المشهد اللي بيكتبه الموديل بيتفحص، بياخد جولة تصليح وحدة، بيستنى المعلم، وما بيدخل الدرس والصفحة إلا بعد الموافقة.",
        "role": "بيفحص 02_question_factory/scene_writer.py (فحص الكود والبرومبت وصفحة التشغيل)، وcore/llm_scenes.py (الطريق كامل)، وأبواب /llm/... بالسيرفر. الموديل وهمي، ما بدها مفاتيح. تشغيل (من جوّا 05_explanation_api): python -m unittest tests.test_llm_scenes -v",
        "how": [
            "GOOD = المثال الجاهز EXAMPLE (كود سليم)، وBAD = كود فيه fetch و while (true).",
            "TestSceneWriter بيفحص قواعد الكود لحالها، بدون سيرفر.",
            "TestPipeline بيعمل كتاب الفيزياء للصف العاشر بمجلد مؤقت خاص فيه.",
            "بعدها بيمشي بالترتيب: توليد، إعادة بدون تكلفة، تصليح، رفض، موافقة المعلم، الصفحة، صفحة التشغيل، الحدود.",
            "TestHTTP بيركّب الموديل الوهمي مكان llm_gateway.generate ومفتاح وهمي، وبيجرّب نفس الطريق عبر الأبواب.",
            "كل كلاس بيرجّع الإعدادات زي ما كانت وبيمسح مجلده بالآخر.",
        ],
        "ideas": [
            ["pending_review", "مشهد نجح بالفحص بس لسا بيستنى المعلم يوافق."],
            ["جولة تصليح", "إذا الكود فشل، الموديل بينقال شو الغلط (REJECTED) وبياخد فرصة وحدة كمان."],
            ["default-src 'none'", "قاعدة أمان (CSP) بصفحة التشغيل بتمنع أي اتصال بالإنترنت."],
            ["include_llm", "خيار بيزيد مشاهد الموديل المقبولة على الدرس؛ بدونه بتطلع مشاهد المصنع بس."],
        ],
        "items": {
            "FakeModel": "موديل وهمي بيرد بالأكواد اللي أعطيناه إياها بالترتيب، وبيعد النداءات.",
            "FakeModel.__init__": "بيحفظ الأكواد، وبيبدأ العدّاد من صفر، وبيجهّز مكان لآخر برومبت.",
            "FakeModel.__call__": "بيزيد العدّاد، بيحفظ البرومبت، وبيرجع الكود التالي جوّا بلوك javascript (والأخير بيتكرر).",
            "TestSceneWriter": "فحوصات قواعد الكود نفسها، بدون سيرفر.",
            "TestSceneWriter.test_example_passes_every_check": "المثال الجاهز ما فيه ولا مشكلة.",
            "TestSceneWriter.test_dangerous_code_is_refused": "window و fetch و while و eval و document و localStorage وحيل الهروب (constructor) كلها بتنرفض مع السبب.",
            "TestSceneWriter.test_arabic_words_inside_strings_are_not_code": "كلمة while جوّا نص عربي، وحلقة for عادية، ما بتنحسب مشكلة.",
            "TestSceneWriter.test_missing_function_and_syntax_errors": "كود بلا function buildScene بينرفض، وقوس مش مسكّر بيطلع unbalanced أو syntax.",
            "TestSceneWriter.test_too_long_is_refused": "كود أطول من MAX_CODE بينرفض «too long».",
            "TestSceneWriter.test_prompt_has_the_rules_the_facts_and_the_age": "البرومبت فيه القواعد، واسم المفهوم، وفكرة المعلم، ونبرة المرحلة الثانوية (calm expert).",
            "TestSceneWriter.test_runner_blocks_the_network_and_carries_the_code": "صفحة التشغيل بتمنع الشبكة، فيها المرحلة، و«</» مهرّبة عشان الكود ما يسكّر الـ script.",
            "TestPipeline": "الطريق كامل مع موديل وهمي: توليد، حفظ، مراجعة، الدرس.",
            "TestPipeline.setUpClass": "بيوجّه الإعدادات لمجلد مؤقت، بينسخ جراف phy_g10 وبيولّده.",
            "TestPipeline.tearDownClass": "بيرجّع المجلدات الأصلية وبيمسح المؤقت.",
            "TestPipeline.test_1_a_good_scene_waits_for_the_teacher": "كود سليم بيصير pending_review بنداء واحد، والحقائق والمرحلة وصلت للموديل، والسجل فيه رسمة المفهوم.",
            "TestPipeline.test_2_asking_again_costs_nothing": "نفس الطلب مرة ثانية بيرجع المحفوظ (reused) بصفر نداءات.",
            "TestPipeline.test_3_a_bad_answer_gets_one_repair_round": "كود غلط ثم سليم: محاولتين ونداءين، والموديل انقاله REJECTED.",
            "TestPipeline.test_4_still_bad_is_rejected_and_never_approved": "غلط مرتين بيصير rejected مع تحذير، والموافقة عليه بترجع BadInput.",
            "TestPipeline.test_5_approved_scenes_join_the_lesson": "بعد موافقة المعلم بيزيد مشهد custom على الدرس مع include_llm بس، ومعه runner_url.",
            "TestPipeline.test_5b_approved_scene_is_inside_the_page": "المشهد الموافق عليه بيطلع جوّا صفحة /explain نفسها، بنفس جدران الأمان.",
            "TestPipeline.test_6_runner_and_browser_report": "صفحة التشغيل فيها الكود والـ SDK والحماية، وتقرير المتصفح بينحفظ ok.",
            "TestPipeline.test_7_limits_and_wrong_input": "max_scenes = 50 بيرجع BadInput، ودرس أو كتاب مش موجود NotFound.",
            "TestPipeline.test_8_no_key_no_call": "بلا مفتاح وبلا موديل بيرجع BadInput وما في نداء.",
            "TestPipeline.test_9_sdk_doc": "sdk_doc فيه SDK.character وقواعد senior وقائمة الممنوعات (window).",
            "TestHTTP": "نفس الطريق عبر أبواب السيرفر، والموديل الوهمي مركّب بالبوابة. بده FastAPI.",
            "TestHTTP.setUpClass": "مجلد مؤقت، موديل ومفتاح وهميين، TestClient، وبيولّد كتاب bio_g12.",
            "TestHTTP.tearDownClass": "بيرجّع الإعدادات والدوال الأصلية وبيمسح المؤقت.",
            "TestHTTP.test_generate_review_lesson_runner": "توليد ثم القائمة ثم صفحة التشغيل ثم الموافقة ثم الدرس مع include_llm ثم التقرير، كله 200.",
            "TestHTTP.test_errors_and_sdk": "كتاب أو مشهد مش موجود 404، و/llm/sdk فيه SDK.character.",
        },
    },

    "05_explanation_api/tests/test_service.py": {
        "title": "فحوصات المدير (الخدمة)",
        "one": "بيتأكد إن core/service.py بيحوّل أي جراف لشرح كامل: كتب ودروس ومفاهيم ورسومات وصفحة، ومادة جديدة بتاخد هويتها.",
        "role": "بيستدعي دوال core/service.py مباشرة (Python عادي، ما بده FastAPI)، وبيقارن مع core/contract.py. تشغيل (من جوّا 05_explanation_api): python -m unittest tests.test_service -v",
        "how": [
            "بيحط EXPLAIN_SEED=0 ومجلد بيانات مؤقت.",
            "TestService بيولّد كتاب النباتات (من ملف) وكتاب الرياضيات (من dict).",
            "بيفحص الدروس والمفاهيم والرسومات وأنواع المشاهد والأخطاء.",
            "TestNewSubjectAndPage بيوجّه الإعدادات لمجلد ثاني خاص فيه وبيولّد كتاب الحاسوب (مادة جديدة).",
            "بيفحص الهوية والشخصيات والأنشطة والصفحة، وإنها نفس الصفحة المنشورة للكتب الـ12.",
            "كل كلاس بيمسح مجلده بالآخر (والثاني بيرجّع الإعدادات).",
        ],
        "ideas": [
            ["BadInput / NotFound", "أخطاء الخدمة: الأول طلب غلط (السيرفر بيرد 400)، والثاني إشي مش موجود (404)."],
            ["SCENE_KINDS", "قائمة أنواع المشاهد اللي الصفحة بتعرف ترسمها (بـ core/contract.py)."],
        ],
        "items": {
            "TestService": "فحوصات الخدمة على كتابي النباتات والرياضيات.",
            "TestService.setUpClass": "بيولّد كتاب النباتات من graph_path وكتاب الرياضيات من graph.",
            "TestService.tearDownClass": "بيمسح مجلد البيانات المؤقت.",
            "TestService.test_generate_every_lesson": "النباتات 3 دروس وأكثر من 50 مشهد، والرياضيات 4 دروس.",
            "TestService.test_books_and_lessons": "list_books بيرجع الكتابين بالزبط، وlist_lessons للرياضيات 4.",
            "TestService.test_lesson_has_scenes_texts_and_picture_urls": "درس l_parts فيه overview ومفاهيم، وكل رسمة إلها رابط /art/...svg لكل مفتاح بـ icons.",
            "TestService.test_every_scene_kind_is_in_the_contract": "بيمر على كل مشهد بكل درس؛ أي نوع مش بـ SCENE_KINDS بيفشّل الفحص.",
            "TestService.test_concept": "get_concept('root') بيرجع درسه l_parts ومشاهده ورابط رسمته.",
            "TestService.test_every_picture_of_every_lesson_exists": "كل رابط رسمة بكل درس بيطلع SVG حقيقي من get_art.",
            "TestService.test_subject_fallback_picture_has_the_name": "شخصية المادة (subj:📜:أهرامات) مكتوب عليها اسم المفهوم.",
            "TestService.test_errors": "بلا جراف أو جراف فاضي BadInput؛ ملف أو درس أو رسمة مش موجودين NotFound.",
            "TestService.test_model_is_optional_and_checked": "موديل وهمي بيبدأ كل فقرة بـ «ببساطة»: الكتاب بيسجّل llm = custom والنص فعلاً تغيّر.",
            "TestNewSubjectAndPage": "مادة جديدة (الحاسوب، الصف السابع) من الجراف للصفحة كاملة، بمجلد بيانات خاص.",
            "TestNewSubjectAndPage.setUpClass": "بيحفظ مجلدات الإعدادات، بيوجّهها لمجلد مؤقت، وبيولّد كتاب الحاسوب.",
            "TestNewSubjectAndPage.tearDownClass": "بيرجّع المجلدات الأصلية وبيمسح المؤقت.",
            "TestNewSubjectAndPage.test_a_new_subject_gets_its_own_identity": "هوية جديدة: 💻، صوت chip، الشخصية «بِتّو»، المرحلة junior، أكثر من 40 مشهد وبلا تحذيرات.",
            "TestNewSubjectAndPage.test_its_characters_are_its_own_with_whole_names": "كل رسمة ليغو أو شخصية 💻؛ المعالج chip والذاكرة drawers، والاسم الطويل بيطلع كامل على سطرين.",
            "TestNewSubjectAndPage.test_every_activity_kind_is_made_for_the_new_subject": "فيه نوع واحد على الأقل من meet/connect/compare/teach/ladder، و8 أنواع مشاهد أو أكثر.",
            "TestNewSubjectAndPage.test_the_page_of_one_book_and_of_all_books": "صفحة الكتاب فيها هويته وعنوانه، وpage_data فيها بس هالكتاب، وكتاب مش موجود NotFound.",
            "TestNewSubjectAndPage.test_the_server_page_of_the_12_samples_is_the_published_page": "صفحة السيرفر للكتب الـ12 هي نفس player/explain.html حرف بحرف، وبعد ما يرجّع الحاسوب الكتب مرتبة حسب الصف.",
            "TestNewSubjectAndPage.test_delete_and_bad_ids": "حذف كتاب مش موجود NotFound، وid زي ../evil BadInput، وجراف بلا دروس BadInput.",
            "TestNewSubjectAndPage.test_drawings_carry_their_own_face_rules": "كل SVG حامل قواعد الوجه تبعته (لأن img ما بيشوف CSS الصفحة): الأطفال وجه مبسوط، والثانوي بلا وجه.",
        },
    },

    # ------------------------------------------------------------------ the FAKE fastapi + pydantic (sandbox only)
    "05_explanation_api/tests/local_stub_only_for_sandbox/fastapi/__init__.py": {
        "title": "نسخة FastAPI وهمية",
        "one": "تقليد صغير جداً لـ FastAPI (تسجيل الأبواب بس) عشان فحوصات HTTP تشتغل ببيئة ما قدرنا ننزّل فيها FastAPI الحقيقي.",
        "role": "مش للإنتاج وما بينشحن مع المشروع. بيقلّد FastAPI و APIRouter و HTTPException و Query اللي بيستوردهم main.py و api/routes.py. إذا FastAPI الحقيقي منزّل (pip install -r requirements.txt) ما بتحتاجه أبداً. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox python -m unittest discover -s tests -v (من جوّا 05_explanation_api)",
        "how": [
            "PYTHONPATH بيخلّي Python يلاقي هالمجلد قبل أي fastapi ثاني.",
            "routes.py بيعمل APIRouter وبيحط @router.get / post / delete فوق كل دالة.",
            "النسخة الوهمية بتسجّل كل باب كـ (الطريقة، المسار، الدالة) بقائمة routes، وبترجع الدالة زي ما هي.",
            "main.py بيعمل FastAPI وبيضيف الراوتر؛ include_router بينسخ الأبواب للتطبيق.",
            "add_middleware ما بيعمل إشي، لأن CORS ما إله دور بالفحص.",
            "TestClient الوهمي (testclient.py) بيقرأ قائمة routes هاي وبيستدعي الدوال.",
        ],
        "ideas": [
            ["stub", "نسخة وهمية بسيطة من مكتبة، فيها بس الأجزاء اللي بدنا إياها عشان الكود يشتغل بالفحص."],
            ["PYTHONPATH", "متغير بيئة بيضيف مجلدات لأول مكان بيدوّر فيه Python على المكتبات."],
        ],
        "tip": "لا تحط هالمجلد على PYTHONPATH إذا FastAPI الحقيقي منزّل: الوهمي رح يغطّي عليه.",
        "items": {
            "HTTPException": "خطأ فيه كود HTTP (زي 404) ورسالة، والدوال بترميه.",
            "HTTPException.__init__": "بيحفظ status_code و detail.",
            "Query": "بيرجع القيمة الافتراضية بس، بدون أي فحص.",
            "APIRouter": "بيجمع الأبواب بقائمة routes.",
            "APIRouter.__init__": "بيبدأ بقائمة routes فاضية.",
            "APIRouter._add": "بيرجع decorator بيسجّل (الطريقة، المسار، الدالة) وبيرجع الدالة نفسها.",
            "APIRouter.get": "بيسجّل باب GET.",
            "APIRouter.post": "بيسجّل باب POST.",
            "APIRouter.delete": "بيسجّل باب DELETE.",
            "FastAPI": "التطبيق: نفس APIRouter بس بيحفظ الإعدادات (زي العنوان) بـ meta.",
            "FastAPI.__init__": "بيحفظ الإعدادات اللي انبعتت بـ meta.",
            "FastAPI.add_middleware": "ما بيعمل إشي (مكانه بس عشان main.py ما يخرب).",
            "FastAPI.include_router": "بيضيف أبواب الراوتر لأبواب التطبيق.",
        },
    },

    "05_explanation_api/tests/local_stub_only_for_sandbox/fastapi/responses.py": {
        "title": "ردود FastAPI الوهمية",
        "one": "أنواع الردود الوهمية (Response و HTMLResponse و RedirectResponse) اللي بيرجعها السيرفر للصفحات والرسومات.",
        "role": "مش للإنتاج. بيقلّد fastapi.responses اللي بيستورد منه api/routes.py (HTMLResponse و Response). مع FastAPI الحقيقي ما بتحتاجه. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox python -m unittest discover -s tests -v",
        "how": [
            "الدالة بالسيرفر بترجع مثلاً HTMLResponse(الصفحة) أو Response(SVG, media_type).",
            "الرد الوهمي بيحفظ المحتوى والنوع والهيدرز والكود بس.",
            "TestClient الوهمي بيحوّله لرد فيه text و headers و status_code.",
        ],
        "items": {
            "Response": "الرد الأساسي: المحتوى، النوع (media_type)، الهيدرز، والكود (افتراضياً 200).",
            "Response.__init__": "بيحفظ الأربع قيم كما هي.",
            "RedirectResponse": "رد تحويل لعنوان ثاني: كود 307 والعنوان بهيدر location.",
            "RedirectResponse.__init__": "بيعمل Response بلا محتوى، بكود 307 وهيدر location.",
            "HTMLResponse": "رد نوعه text/html (للصفحات).",
            "HTMLResponse.__init__": "بيعمل Response بنوع text/html.",
        },
    },

    "05_explanation_api/tests/local_stub_only_for_sandbox/fastapi/testclient.py": {
        "title": "عميل فحص وهمي",
        "one": "TestClient وهمي بيلاقي الباب المناسب للعنوان وبيستدعي دالته مباشرة، بدون شبكة، وبيرجع رد بشكل الحقيقي.",
        "role": "مش للإنتاج. بيقلّد fastapi.testclient.TestClient اللي بتستعمله test_api.py و test_lego_api.py و test_llm_scenes.py. مع FastAPI الحقيقي ما بتحتاجه. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox python -m unittest discover -s tests -v",
        "how": [
            "بيفصل العنوان لمسار وquery، وبيدمج معها params إذا انبعتت.",
            "بيمر على أبواب التطبيق ويوقف عند أول باب طريقته نفس الطريقة ومساره بيطابق.",
            "{book_id} وأمثالها بيصيروا جزء بيطابق أي نص بلا /، وبياخد قيمته (بعد فك الترميز).",
            "باقي معاملات الدالة: إذا نوعها BaseModel بيبنيه من الـ JSON المبعوث، غير هيك بياخدها من الـ query.",
            "بيستدعي الدالة؛ إذا رمت HTTPException بيرجع كودها ومعه detail.",
            "إذا رجعت Response بياخد محتواها وهيدرزها ونوعها، وإذا BaseModel بيحوّله dict، وغير هيك JSON بكود 200.",
            "إذا ما لقى ولا باب بيرجع 404.",
        ],
        "ideas": [
            ["TestClient", "بيبعت طلبات للتطبيق من جوّا الفحص كأنه متصفح، بدون ما يشغّل سيرفر."],
        ],
        "tip": "ما بيحوّل الأنواع ولا بيفحص الطلب: قيمة الـ query بتوصل نص، وما في 422 زي FastAPI الحقيقي. عشان هيك الفحوصات الحقيقية لازم تنعاد مع FastAPI الأصلي.",
        "items": {
            "_R": "الرد الوهمي اللي بيرجعه العميل: الكود والنص والهيدرز.",
            "_R.__init__": "بيحفظ status_code والنص والهيدرز.",
            "_R.json": "بيقرأ النص كـ JSON.",
            "_R.text": "بيرجع النص زي ما هو.",
            "TestClient": "العميل الوهمي: بيستدعي دوال الأبواب مباشرة.",
            "TestClient.__init__": "بيحفظ التطبيق.",
            "TestClient._go": "القلب: بيلاقي الباب، بيجهّز المعاملات، بيستدعي الدالة، وبيحوّل نتيجتها لرد (أو 404).",
            "TestClient.get": "طلب GET (مع params اختيارية).",
            "TestClient.post": "طلب POST مع JSON.",
            "TestClient.delete": "طلب DELETE.",
        },
    },

    "05_explanation_api/tests/local_stub_only_for_sandbox/fastapi/middleware/__init__.py": {
        "title": "حزمة الوسطاء الوهمية",
        "one": "ملف فاضي بيخلّي fastapi/middleware الوهمي حزمة.",
        "role": "مش للإنتاج. وجوده بس عشان سطر from fastapi.middleware.cors import CORSMiddleware بـ main.py يشتغل مع النسخة الوهمية. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox",
        "how": [
            "main.py بيستورد fastapi.middleware.cors.",
            "Python بيلاقي هالملف فبيعتبر middleware حزمة وبيكمل لـ cors.py.",
        ],
        "items": {},
    },

    "05_explanation_api/tests/local_stub_only_for_sandbox/fastapi/middleware/cors.py": {
        "title": "CORS وهمي",
        "one": "كلاس CORSMiddleware فاضي، بس عشان الاستيراد بـ main.py ما يخرب.",
        "role": "مش للإنتاج. main.py بيضيف CORSMiddleware للتطبيق؛ بالنسخة الوهمية add_middleware ما بيعمل إشي، فالكلاس ما بيلزمه محتوى. مع FastAPI الحقيقي ما بتحتاجه. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox",
        "how": [
            "main.py بيستورد CORSMiddleware وبيعطيه لـ app.add_middleware.",
            "النسخة الوهمية بتتجاهله، لأن الفحص ما بيمر من متصفح.",
        ],
        "ideas": [
            ["CORS", "إذن بيسمح لصفحة من موقع ثاني تطلب من السيرفر؛ بيهم المتصفح بس."],
        ],
        "items": {
            "CORSMiddleware": "كلاس فاضي، مكانه بس عشان الاستيراد.",
        },
    },

    "05_explanation_api/tests/local_stub_only_for_sandbox/pydantic/__init__.py": {
        "title": "نسخة pydantic وهمية",
        "one": "تقليد صغير لـ pydantic: BaseModel و Field بس، عشان أشكال الطلبات بـ api/schemas.py تنقرأ بالـ sandbox.",
        "role": "مش للإنتاج وما بينشحن. api/schemas.py بيعرّف أشكال الطلبات والردود بـ BaseModel و Field. مع pydantic الحقيقي (بيجي مع FastAPI) ما بتحتاجه. بالـ sandbox بس: PYTHONPATH=tests/local_stub_only_for_sandbox python -m unittest discover -s tests -v",
        "how": [
            "Field(default, ...) بيحفظ القيمة الافتراضية بس وبيتجاهل الباقي (الوصف والحدود).",
            "BaseModel(**kw) بيمر على الحقول المكتوبة بالكلاس (annotations).",
            "لكل حقل بياخد قيمته من kw، وإذا مش موجودة بياخد الافتراضية.",
            "model_dump بيرجع الحقول كـ dict، والـ TestClient الوهمي بيحوّلها JSON.",
        ],
        "tip": "ما في أي فحص للأنواع أو الحدود: طلب غلط ما بيوقف هون زي pydantic الحقيقي.",
        "items": {
            "_F": "علبة صغيرة بتحفظ القيمة الافتراضية لحقل.",
            "_F.__init__": "بيحفظ default وبيتجاهل الباقي.",
            "Field": "بيرجع _F فيه القيمة الافتراضية.",
            "BaseModel": "أساس أشكال الطلبات: بيعبّي الحقول من القيم المبعوثة.",
            "BaseModel.__init__": "لكل حقل مكتوب بالكلاس: القيمة المبعوثة أو الافتراضية.",
            "BaseModel.model_dump": "بيرجع كل الحقول كـ dict.",
        },
    },

    # ------------------------------------------------------------------ browser tests (05_explanation_api/tests_browser)
    "05_explanation_api/tests_browser/test_lego_page.py": {
        "title": "الليغو بمتصفح حقيقي",
        "one": "بيتأكد بمتصفح حقيقي إن رسومات الليغو بالصفحة هي نفسها اللي بيرسمها السيرفر، وإن كتاب مادة جديدة بيشتغل كامل بلا أخطاء.",
        "role": "بيفحص 02_question_factory/lego.py و explain_main و player/build_explain_player.py ورسم core/art.py، مع كود الصفحة (window.__ART.legoSVG). مش unittest: سكربت بيطبع ✅ و ❌. بده playwright ومتصفح Chromium تبعه. تشغيل (من جوّا 05_explanation_api): python tests_browser/test_lego_page.py",
        "how": [
            "بيوجّه مكتبة الليغو لملف مؤقت فاضي، فالرسومات بتيجي من الكلمات بس (بلا موديل).",
            "بيولّد كتاب الحاسوب بالمصنع (explain_main.run) وبيبني صفحته بملف HTML مؤقت.",
            "بيفتح الصفحة بـ Chromium وبيمنع الخطوط من النت.",
            "(1) بيبني مفاتيح ليغو لكل قطعة مع شارات وألوان وحركات، وبيقارن رسمة الصفحة برسمة Python حرف بحرف.",
            "(2) بيتأكد إن كل مفهوم بالحاسوب إله رسمة ليغو، وإن الشخصيات مرسومة وبتتحرك وإلها حجم حقيقي.",
            "بيكبس «التالي» لآخر كل درس وبيعد الخطوات وأي خطأ JS.",
            "(3) بيقرأ الصفحة المنشورة للكتب الـ12 وبيتأكد ما فيها ولا مفتاح ليغو (ما تغيّرت).",
            "بالآخر بيطبع الفاشل، وعدد الناجح والفاشل، وأخطاء JS.",
        ],
        "ideas": [
            ["Playwright", "مكتبة بتشغّل متصفح حقيقي من Python: بتفتح صفحات، بتكبس، وبتشغّل JS جوّا الصفحة."],
            ["pageerror", "حدث بيصير لما يطلع خطأ JS بالصفحة؛ الفحص بيجمعهم."],
        ],
        "tip": "بطيء شوي لأنه بيمشي كل خطوة؛ شغّله بعد ما تغيّر lego.py أو رسم الليغو بالصفحة.",
        "items": {
            "ok": "بيسجّل نتيجة فحص (✅ أو ❌ مع شوية تفاصيل) بقائمة res.",
        },
    },

    "05_explanation_api/tests_browser/test_server_page.py": {
        "title": "صفحة السيرفر بالمتصفح",
        "one": "بيتأكد بمتصفح حقيقي إن الصفحة اللي بيعطيها السيرفر لمادة جديدة بتشتغل: صوتها وشخصياتها وألوانها وشخصيتها الترحيبية، وكل خطوة بلا أخطاء.",
        "role": "بيفحص core/service.py (generate و page_html) و core/art.py مع كود الصفحة (window.__ART و window.__SOUND). مش unittest: سكربت بيطبع ✅ و ❌ وبيطلع بكود 1 إذا في فشل. بده playwright ومتصفح Chromium تبعه. تشغيل (من جوّا 05_explanation_api): python tests_browser/test_server_page.py",
        "how": [
            "بيحط مجلد بيانات مؤقت و EXPLAIN_SEED=0.",
            "بيولّد كتاب الحاسوب، وكتاب ثاني «عالم الحشرات» (نفس الجراف باسم ما بتعرفه ولا كلمة عنا).",
            "(1) بيقارن رسمة شخصية المادة بالصفحة وبـ Python لكل شكل مادة مع أسماء طويلة وقصيرة.",
            "(2) لكل كتاب من الاثنين بيفتح صفحته وبيتأكد من آلته الموسيقية الخاصة.",
            "بيتأكد إن كل رسوماته ليغو أو شخصية مادته، وإنه في 3 ألوان أو أكثر.",
            "بيحوّل الصفحة لشكل الأطفال وبيدوّر على اسم الشخصية الترحيبية، وبيكبس على شخصية وبيستنى نغمة.",
            "بيمشي كل خطوات كل درس وبيتأكد ما في أخطاء JS.",
            "(4) بيشغّل الآلات الجديدة chip و harp و vibes و steel: مسموعة، ما بتشوّش، وكل وحدة صوتها غير.",
            "بيطبع المجموع، وبيطلع بكود 1 إذا في فحص فشل.",
        ],
        "ideas": [
            ["Playwright", "مكتبة بتشغّل متصفح حقيقي من Python: بتفتح صفحات، بتكبس، وبتشغّل JS جوّا الصفحة."],
            ["peak", "أعلى ارتفاع للصوت؛ قريب من 1 يعني تشويش، وقريب من 0 يعني مش مسموع."],
        ],
        "items": {
            "ok": "بيطبع ✅ أو ❌ مع وصف الفحص، وبيحطه بقائمة الناجح أو الفاشل.",
            "page_file": "بيكتب صفحة السيرفر (service.page_html) لكتب معيّنة بملف مؤقت وبيرجع رابط file://.",
            "page_data": "بيطلّع البيانات (const DATA) من نص الصفحة، لأن الصفحة مخبّيتها جوّا دالتها.",
        },
    },
}
